[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework ="#custom"
  command = "npm run dev:vue-cli"
  targetPort = 4999
  port = 5000
  publish = "dist"
  autoLaunch = true